# .github/workflows/deploy.yml
name: Deploy FastAPI to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.HOST_IP }} >> ~/.ssh/known_hosts

    - name: Deploy app to EC2
      run: |
        ssh ${{ secrets.USER }}@${{ secrets.HOST_IP }} << 'EOF'
          # Clean up previous deployment
          sudo rm -rf personal_gpt || true

          # Clone the latest code
          git clone https://github.com/zamanrahimi/personal_gpt.git
          cd personal_gpt/app

          # Stop and remove any existing container
          sudo docker stop fastapi-container || true
          sudo docker rm fastapi-container || true

          # Build and run the Docker container
          sudo docker build -t fastapi-app .
          sudo docker run -d -p 80:80 --name fastapi-container fastapi-app
        EOF
